--DROP TABLE IF EXISTS answer;
--DROP TABLE IF EXISTS question;

CREATE TABLE question (
id BIGSERIAL PRIMARY KEY,
title VARCHAR (128) NOT NULL,
text VARCHAR (512) NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE answer (
id BIGSERIAL PRIMARY KEY,
question_id BIGINT NOT NULL,
title VARCHAR (128) NOT NULL,
text VARCHAR (2048) NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
FOREIGN KEY (question_id) REFERENCES question(id)
);